#region Copyright
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="PartialOutput.cs" company="Ian Horswill">
// Copyright (C) 2020 Ian Horswill
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in the
// Software without restriction, including without limitation the rights to use, copy,
// modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
// and to permit persons to whom the Software is furnished to do so, subject to the
// following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
// PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
// OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------
#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace Step.Interpreter
{
    /// <summary>
    /// Tracks the output buffer and state of the text generated by a task.
    /// The buffer is writable but the PartialOutput object is read-only.
    /// Calling Append will write the buffer but return a new PartialOutput
    /// struct, that is also read-only.
    /// The read-only-ness is to make backtracking easy.
    /// </summary>
    [DebuggerDisplay("{" + nameof(AsString) + "}")]
    public readonly struct PartialOutput
    {
        /// <summary>
        /// Fixed buffer in which to hold the output
        /// </summary>
        public readonly string[] Buffer;
        /// <summary>
        /// Amount of Buffer currently in use.
        /// The output generated so far is in cells Buffer[0 ... Length-1]
        /// </summary>
        public readonly int Length;

        private PartialOutput(string[] buffer, int length)
        {
            Buffer = buffer;
            Length = length;
        }

        private const int DefaultCapacity = 500;

        /// <summary>
        /// Make an empty PartialOutput with a new buffer.
        /// </summary>
        public PartialOutput(int capacity)
            : this(new string[capacity])
        { }

        /// <summary>
        /// Make an empty PartialOutput that stores output in the specified buffer.
        /// </summary>
        /// <param name="buffer"></param>
        public PartialOutput(string[] buffer) : this(buffer, 0) { }

        /// <summary>
        /// Make an empty PartialOutput with a new buffer.
        /// </summary>
        public static PartialOutput NewEmpty() => new PartialOutput(DefaultCapacity);

        /// <summary>
        /// Add tokens to buffer and return a new PartialOutput with the updated length.
        /// Upon backtracking, the new PartialOutput can be thrown away and this one
        /// reused.
        /// </summary>
        /// <param name="tokens">Tokens to add to output</param>
        /// <returns>New buffer state</returns>
        public PartialOutput Append(params string[] tokens)
        {
            Array.Copy(tokens, 0, Buffer, Length, tokens.Length);
            return new PartialOutput(Buffer, Length + tokens.Length);
        }

        /// <summary>
        /// Add tokens to buffer and return a new PartialOutput with the updated length.
        /// Upon backtracking, the new PartialOutput can be thrown away and this one
        /// reused.
        /// </summary>
        /// <param name="tokens">Tokens to add to output</param>
        /// <returns>New buffer state</returns>
        public PartialOutput Append(IEnumerable<string> tokens)
        {
            var count = 0;
            foreach (var token in tokens) Buffer[Length + count++] = token;
            return new PartialOutput(Buffer, Length + count);
        }

        /// <summary>
        /// Tokens output so far.
        /// </summary>
        public IEnumerable<string> Output
        {
            get
            {
                for (var i = 0; i < Length; i++)
                    yield return Buffer[i];
            }
        }

        /// <summary>
        /// The text generated so far, as a single string.
        /// </summary>
        public string AsString => Output.Untokenize();

        /// <inheritdoc />
        public override string ToString() => AsString;
    }
}
