using Step.Output;

namespace Step
{
    /// <summary>
    /// Used by TextUtilities.Untokenize to regenerate a string from the tokens generated by the Step code.
    /// </summary>
    public class FormattingOptions
    {
        /// <summary>
        /// Default token filters to use.
        /// </summary>
        public static readonly TokenFilter[] DefaultTokenFilters = { AOrAnFilter.Instance, VerbConjugationFilter.Instance };

        /// <summary>
        /// Default formatting options
        /// </summary>
        public static FormattingOptions Default = new FormattingOptions();
        /// <summary>
        /// If true, capitalize words after a sentence-terminating period.
        /// </summary>
        public bool Capitalize = true;
        /// <summary>
        /// If true, include two spaces after a sentence-terminating period rather than one.
        /// </summary>
        public bool FrenchSpacing = true;
        /// <summary>
        /// Text to mark the end of a line
        /// </summary>
        public string LineSeparator = "\n";
        /// <summary>
        /// Text marking the end of a paragraph
        /// </summary>
        public string ParagraphMarker = "\n\n";
        /// <summary>
        /// Ignore paragraph and newline marks at the beginning of the output
        /// </summary>
        public bool SuppressLeadingVerticalSpace = true;

        /// <summary>
        /// TokenFilters to apply during output
        /// </summary>
        public TokenFilter[] TokenFilters = DefaultTokenFilters;
    }
}
